language: c
sudo: required
dist: trusty
before_script:
  - mkdir build
  - cd build
matrix:
  include:
    - compiler: gcc
      script: cmake -DCGI_WITH_FCGI:BOOL=OFF .. && make
    - compiler: clang
      script: cmake -DCGI_WITH_FCGI:BOOL=OFF .. && make
    - compiler: gcc
      addons:
        apt:
          packages:
            - libfcgi-dev
      script: cmake -DCGI_WITH_FCGI:BOOL=ON .. && make
    - compiler: clang
      addons:
        apt:
          packages:
            - libfcgi-dev
      script: cmake -DCGI_WITH_FCGI:BOOL=ON .. && make
